version: '2.0'
services:
  rasa:
    image: rasa/rasa:1.10.14-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: kyowawa/winebot19:new_actions
    expose: [5055]